<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Authentication;

use Core\Authentication\CoreAuth;
use Core\Request\Parameters\HeaderParam;

/**
 * Utility class for authorization and token management.
 */
class MppTokenManager extends CoreAuth implements MppTokenCredentials
{
    private $authorization;

    /**
     * Returns an instance of this class.
     *
     * @param string $authorization Digital Payments access token ([How to obtain Digital Payments
     *        access token?](page:guided-walkthrough/walkthrough1))
     */
    public function __construct(string $authorization)
    {
        parent::__construct(HeaderParam::init('Authorization', $authorization)->requiredNonEmpty());
        $this->authorization = $authorization;
    }

    /**
     * String value for authorization.
     */
    public function getAuthorization(): string
    {
        return $this->authorization;
    }

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $authorization Digital Payments access token ([How to obtain Digital Payments
     *        access token?](page:guided-walkthrough/walkthrough1))
     */
    public function equals(string $authorization): bool
    {
        return $authorization == $this->authorization;
    }
}
