<?php

declare(strict_types=1);

/*
 * ShellSmartPayAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellSmartPayAPILib\Authentication;

/**
 * Interface for defining the behavior of Authentication.
 */
interface MppTokenCredentials
{
    /**
     * String value for authorization.
     */
    public function getAuthorization(): string;

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $authorization Access token to be passed for Mobile Payment Platform
     *        Authentication ([How to obtain Digital Payments access token?](page:guided-
     *        walkthrough/walkthrough1))
     */
    public function equals(string $authorization): bool;
}
