<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Authentication;

/**
 * Interface for defining the behavior of Authentication.
 */
interface MppTokenCredentials
{
    /**
     * String value for authorization.
     */
    public function getAuthorization(): string;

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $authorization Digital Payments access token ([How to obtain Digital Payments
     *        access token?](page:guided-walkthrough/walkthrough1))
     */
    public function equals(string $authorization): bool;
}
