<?php

declare(strict_types=1);

/*
 * ShellSmartPayAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellSmartPayAPILib\Authentication;

use Core\Authentication\CoreAuth;
use ShellSmartPayAPILib\ConfigurationDefaults;
use Core\Request\Parameters\HeaderParam;

/**
 * Utility class for authorization and token management.
 */
class MppTokenManager extends CoreAuth implements MppTokenCredentials
{
    /**
     * @var array
     */
    private $config;

    public function __construct(array $config)
    {
        $this->config = $config;
        parent::__construct(HeaderParam::init('Authorization', $this->getAuthorization())->requiredNonEmpty());
    }

    /**
     * String value for authorization.
     */
    public function getAuthorization(): string
    {
        return $this->config['authorization'] ?? ConfigurationDefaults::AUTHORIZATION;
    }

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $authorization Access token to be passed for Mobile Payment Platform
     *        Authentication ([How to obtain Digital Payments access token?](page:guided-
     *        walkthrough/walkthrough1))
     */
    public function equals(string $authorization): bool
    {
        return $authorization == $this->getAuthorization();
    }
}
