<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Authentication;

use Core\Authentication\CoreAuth;
use Core\Request\Parameters\HeaderParam;

/**
 * Utility class for authorization and token management.
 */
class OAuthTokenPostManager extends CoreAuth implements OAuthTokenPostCredentials
{
    private $xApigeeAuthorization;

    /**
     * Returns an instance of this class.
     *
     * @param string $xApigeeAuthorization APIGEE access token ([How to obtain APIGEE access
     *        token?](page:guided-walkthrough/walkthrough1))
     */
    public function __construct(string $xApigeeAuthorization)
    {
        parent::__construct(HeaderParam::init('X-Apigee-Authorization', $xApigeeAuthorization)->requiredNonEmpty());
        $this->xApigeeAuthorization = $xApigeeAuthorization;
    }

    /**
     * String value for xApigeeAuthorization.
     */
    public function getXApigeeAuthorization(): string
    {
        return $this->xApigeeAuthorization;
    }

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $xApigeeAuthorization APIGEE access token ([How to obtain APIGEE access
     *        token?](page:guided-walkthrough/walkthrough1))
     */
    public function equals(string $xApigeeAuthorization): bool
    {
        return $xApigeeAuthorization == $this->xApigeeAuthorization;
    }
}
