<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Authentication;

/**
 * Interface for defining the behavior of Authentication.
 */
interface OAuthTokenPostCredentials
{
    /**
     * String value for xApigeeAuthorization.
     */
    public function getXApigeeAuthorization(): string;

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $xApigeeAuthorization APIGEE access token ([How to obtain APIGEE access
     *        token?](page:guided-walkthrough/walkthrough1))
     */
    public function equals(string $xApigeeAuthorization): bool;
}
