<?php

declare(strict_types=1);

/*
 * ShellSmartPayAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellSmartPayAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellSmartPayAPILib\Models\AccessTokenResponse;

/**
 * Builder for model AccessTokenResponse
 *
 * @see AccessTokenResponse
 */
class AccessTokenResponseBuilder
{
    /**
     * @var AccessTokenResponse
     */
    private $instance;

    private function __construct(AccessTokenResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Access Token Response Builder object.
     */
    public static function init(): self
    {
        return new self(new AccessTokenResponse());
    }

    /**
     * Sets access token field.
     *
     * @param string|null $value
     */
    public function accessToken(?string $value): self
    {
        $this->instance->setAccessToken($value);
        return $this;
    }

    /**
     * Sets expires in field.
     *
     * @param string|null $value
     */
    public function expiresIn(?string $value): self
    {
        $this->instance->setExpiresIn($value);
        return $this;
    }

    /**
     * Sets token type field.
     *
     * @param string|null $value
     */
    public function tokenType(?string $value): self
    {
        $this->instance->setTokenType($value);
        return $this;
    }

    /**
     * Initializes a new Access Token Response object.
     */
    public function build(): AccessTokenResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
