<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellEVLib\Models\AccessTokenResponse;

/**
 * Builder for model AccessTokenResponse
 *
 * @see AccessTokenResponse
 */
class AccessTokenResponseBuilder
{
    /**
     * @var AccessTokenResponse
     */
    private $instance;

    private function __construct(AccessTokenResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new access token response Builder object.
     */
    public static function init(): self
    {
        return new self(new AccessTokenResponse());
    }

    /**
     * Sets access token field.
     */
    public function accessToken(?string $value): self
    {
        $this->instance->setAccessToken($value);
        return $this;
    }

    /**
     * Sets expires in field.
     */
    public function expiresIn(?string $value): self
    {
        $this->instance->setExpiresIn($value);
        return $this;
    }

    /**
     * Sets token type field.
     */
    public function tokenType(?string $value): self
    {
        $this->instance->setTokenType($value);
        return $this;
    }

    /**
     * Initializes a new access token response object.
     */
    public function build(): AccessTokenResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
