<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellEVLib\Models\AroundLocationArray;

/**
 * Builder for model AroundLocationArray
 *
 * @see AroundLocationArray
 */
class AroundLocationArrayBuilder
{
    /**
     * @var AroundLocationArray
     */
    private $instance;

    private function __construct(AroundLocationArray $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new around location array Builder object.
     */
    public static function init(array $data): self
    {
        return new self(new AroundLocationArray($data));
    }

    /**
     * Initializes a new around location array object.
     */
    public function build(): AroundLocationArray
    {
        return CoreHelper::clone($this->instance);
    }
}
