<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellEVLib\Models\AroundLocationArrayDataItemsOpeningHoursItems;

/**
 * Builder for model AroundLocationArrayDataItemsOpeningHoursItems
 *
 * @see AroundLocationArrayDataItemsOpeningHoursItems
 */
class AroundLocationArrayDataItemsOpeningHoursItemsBuilder
{
    /**
     * @var AroundLocationArrayDataItemsOpeningHoursItems
     */
    private $instance;

    private function __construct(AroundLocationArrayDataItemsOpeningHoursItems $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new around location array data items opening hours items Builder object.
     */
    public static function init(): self
    {
        return new self(new AroundLocationArrayDataItemsOpeningHoursItems());
    }

    /**
     * Sets closing from hours field.
     */
    public function closingFromHours(?string $value): self
    {
        $this->instance->setClosingFromHours($value);
        return $this;
    }

    /**
     * Sets closing from minutes field.
     */
    public function closingFromMinutes(?string $value): self
    {
        $this->instance->setClosingFromMinutes($value);
        return $this;
    }

    /**
     * Sets closing to hours field.
     */
    public function closingToHours(?string $value): self
    {
        $this->instance->setClosingToHours($value);
        return $this;
    }

    /**
     * Sets closing to minutes field.
     */
    public function closingToMinutes(?string $value): self
    {
        $this->instance->setClosingToMinutes($value);
        return $this;
    }

    /**
     * Sets from day field.
     */
    public function fromDay(?string $value): self
    {
        $this->instance->setFromDay($value);
        return $this;
    }

    /**
     * Sets opening from hours field.
     */
    public function openingFromHours(?string $value): self
    {
        $this->instance->setOpeningFromHours($value);
        return $this;
    }

    /**
     * Sets opening from minutes field.
     */
    public function openingFromMinutes(?string $value): self
    {
        $this->instance->setOpeningFromMinutes($value);
        return $this;
    }

    /**
     * Sets opening to hours field.
     */
    public function openingToHours(?string $value): self
    {
        $this->instance->setOpeningToHours($value);
        return $this;
    }

    /**
     * Sets opening to minutes field.
     */
    public function openingToMinutes(?string $value): self
    {
        $this->instance->setOpeningToMinutes($value);
        return $this;
    }

    /**
     * Sets to day field.
     */
    public function toDay(?string $value): self
    {
        $this->instance->setToDay($value);
        return $this;
    }

    /**
     * Initializes a new around location array data items opening hours items object.
     */
    public function build(): AroundLocationArrayDataItemsOpeningHoursItems
    {
        return CoreHelper::clone($this->instance);
    }
}
