<?php

declare(strict_types=1);

/*
 * ShellSmartPayAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellSmartPayAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellSmartPayAPILib\Models\AroundLocationArray;
use ShellSmartPayAPILib\Models\Datum;

/**
 * Builder for model AroundLocationArray
 *
 * @see AroundLocationArray
 */
class AroundLocationArrayBuilder
{
    /**
     * @var AroundLocationArray
     */
    private $instance;

    private function __construct(AroundLocationArray $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Around Location Array Builder object.
     *
     * @param Datum[] $data
     */
    public static function init(array $data): self
    {
        return new self(new AroundLocationArray($data));
    }

    /**
     * Initializes a new Around Location Array object.
     */
    public function build(): AroundLocationArray
    {
        return CoreHelper::clone($this->instance);
    }
}
