<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellEVLib\Models\AroundLocationArrayDataItemsLoc;

/**
 * Builder for model AroundLocationArrayDataItemsLoc
 *
 * @see AroundLocationArrayDataItemsLoc
 */
class AroundLocationArrayDataItemsLocBuilder
{
    /**
     * @var AroundLocationArrayDataItemsLoc
     */
    private $instance;

    private function __construct(AroundLocationArrayDataItemsLoc $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new around location array data items loc Builder object.
     */
    public static function init(string $country, string $ccode): self
    {
        return new self(new AroundLocationArrayDataItemsLoc($country, $ccode));
    }

    /**
     * Sets street field.
     */
    public function street(?string $value): self
    {
        $this->instance->setStreet($value);
        return $this;
    }

    /**
     * Sets pc field.
     */
    public function pc(?string $value): self
    {
        $this->instance->setPc($value);
        return $this;
    }

    /**
     * Sets city field.
     */
    public function city(?string $value): self
    {
        $this->instance->setCity($value);
        return $this;
    }

    /**
     * Sets region field.
     */
    public function region(?string $value): self
    {
        $this->instance->setRegion($value);
        return $this;
    }

    /**
     * Initializes a new around location array data items loc object.
     */
    public function build(): AroundLocationArrayDataItemsLoc
    {
        return CoreHelper::clone($this->instance);
    }
}
