<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellEVLib\Models\AroundLocationArrayDataItems;
use ShellEVLib\Models\AroundLocationArrayDataItemsLoc;

/**
 * Builder for model AroundLocationArrayDataItems
 *
 * @see AroundLocationArrayDataItems
 */
class AroundLocationArrayDataItemsBuilder
{
    /**
     * @var AroundLocationArrayDataItems
     */
    private $instance;

    private function __construct(AroundLocationArrayDataItems $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new around location array data items Builder object.
     */
    public static function init(
        string $id,
        int $type,
        string $name,
        string $addr,
        float $lat,
        float $lon,
        array $amen,
        array $fuel,
        AroundLocationArrayDataItemsLoc $loc,
        string $mppStationId
    ): self {
        return new self(
            new AroundLocationArrayDataItems(
                $id,
                $type,
                $name,
                $addr,
                $lat,
                $lon,
                $amen,
                $fuel,
                $loc,
                $mppStationId
            )
        );
    }

    /**
     * Sets double site id field.
     */
    public function doubleSiteId(?string $value): self
    {
        $this->instance->setDoubleSiteId($value);
        return $this;
    }

    /**
     * Sets opening hours field.
     */
    public function openingHours(?array $value): self
    {
        $this->instance->setOpeningHours($value);
        return $this;
    }

    /**
     * Sets telephone field.
     */
    public function telephone(?string $value): self
    {
        $this->instance->setTelephone($value);
        return $this;
    }

    /**
     * Sets authorisation code field.
     */
    public function authorisationCode(?string $value): self
    {
        $this->instance->setAuthorisationCode($value);
        return $this;
    }

    /**
     * Sets mp preauth field.
     */
    public function mpPreauth(?int $value): self
    {
        $this->instance->setMpPreauth($value);
        return $this;
    }

    /**
     * Initializes a new around location array data items object.
     */
    public function build(): AroundLocationArrayDataItems
    {
        return CoreHelper::clone($this->instance);
    }
}
