<?php

declare(strict_types=1);

/*
 * ShellSmartPayAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellSmartPayAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellSmartPayAPILib\Models\CancelFuelingRequest;

/**
 * Builder for model CancelFuelingRequest
 *
 * @see CancelFuelingRequest
 */
class CancelFuelingRequestBuilder
{
    /**
     * @var CancelFuelingRequest
     */
    private $instance;

    private function __construct(CancelFuelingRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Cancel Fueling Request Builder object.
     */
    public static function init(): self
    {
        return new self(new CancelFuelingRequest());
    }

    /**
     * Sets mpp Transaction Id field.
     *
     * @param string|null $value
     */
    public function mppTransactionId(?string $value): self
    {
        $this->instance->setMppTransactionId($value);
        return $this;
    }

    /**
     * Sets reason Code field.
     *
     * @param string|null $value
     */
    public function reasonCode(?string $value): self
    {
        $this->instance->setReasonCode($value);
        return $this;
    }

    /**
     * Initializes a new Cancel Fueling Request object.
     */
    public function build(): CancelFuelingRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
