<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellEVLib\Models\CancelFuelingErrorResponse;

/**
 * Builder for model CancelFuelingErrorResponse
 *
 * @see CancelFuelingErrorResponse
 */
class CancelFuelingErrorResponseBuilder
{
    /**
     * @var CancelFuelingErrorResponse
     */
    private $instance;

    private function __construct(CancelFuelingErrorResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new cancel fueling error response Builder object.
     */
    public static function init(): self
    {
        return new self(new CancelFuelingErrorResponse());
    }

    /**
     * Sets error code field.
     */
    public function errorCode(?string $value): self
    {
        $this->instance->setErrorCode($value);
        return $this;
    }

    /**
     * Sets error description field.
     */
    public function errorDescription(?string $value): self
    {
        $this->instance->setErrorDescription($value);
        return $this;
    }

    /**
     * Sets errors field.
     */
    public function errors(?array $value): self
    {
        $this->instance->setErrors($value);
        return $this;
    }

    /**
     * Initializes a new cancel fueling error response object.
     */
    public function build(): CancelFuelingErrorResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
