<?php

declare(strict_types=1);

/*
 * ShellSmartPayAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellSmartPayAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellSmartPayAPILib\Models\CancelFuelingErrorResponse;
use ShellSmartPayAPILib\Models\MppError;

/**
 * Builder for model CancelFuelingErrorResponse
 *
 * @see CancelFuelingErrorResponse
 */
class CancelFuelingErrorResponseBuilder
{
    /**
     * @var CancelFuelingErrorResponse
     */
    private $instance;

    private function __construct(CancelFuelingErrorResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Cancel Fueling Error Response Builder object.
     */
    public static function init(): self
    {
        return new self(new CancelFuelingErrorResponse());
    }

    /**
     * Sets error Code field.
     *
     * @param string|null $value
     */
    public function errorCode(?string $value): self
    {
        $this->instance->setErrorCode($value);
        return $this;
    }

    /**
     * Sets error Description field.
     *
     * @param string|null $value
     */
    public function errorDescription(?string $value): self
    {
        $this->instance->setErrorDescription($value);
        return $this;
    }

    /**
     * Sets errors field.
     *
     * @param MppError[]|null $value
     */
    public function errors(?array $value): self
    {
        $this->instance->setErrors($value);
        return $this;
    }

    /**
     * Initializes a new Cancel Fueling Error Response object.
     */
    public function build(): CancelFuelingErrorResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
