<?php

declare(strict_types=1);

/*
 * ShellSmartPayAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellSmartPayAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellSmartPayAPILib\Models\CollectingCompany;

/**
 * Builder for model CollectingCompany
 *
 * @see CollectingCompany
 */
class CollectingCompanyBuilder
{
    /**
     * @var CollectingCompany
     */
    private $instance;

    private function __construct(CollectingCompany $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Collecting Company Builder object.
     *
     * @param string $colCoId
     */
    public static function init(string $colCoId): self
    {
        return new self(new CollectingCompany($colCoId));
    }

    /**
     * Initializes a new Collecting Company object.
     */
    public function build(): CollectingCompany
    {
        return CoreHelper::clone($this->instance);
    }
}
