<?php

declare(strict_types=1);

/*
 * ShellSmartPayAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellSmartPayAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellSmartPayAPILib\Models\DeviceDetail;

/**
 * Builder for model DeviceDetail
 *
 * @see DeviceDetail
 */
class DeviceDetailBuilder
{
    /**
     * @var DeviceDetail
     */
    private $instance;

    private function __construct(DeviceDetail $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Device Detail Builder object.
     */
    public static function init(): self
    {
        return new self(new DeviceDetail());
    }

    /**
     * Sets device Id field.
     *
     * @param string|null $value
     */
    public function deviceId(?string $value): self
    {
        $this->instance->setDeviceId($value);
        return $this;
    }

    /**
     * Sets model field.
     *
     * @param string|null $value
     */
    public function model(?string $value): self
    {
        $this->instance->setModel($value);
        return $this;
    }

    /**
     * Sets os Version field.
     *
     * @param string|null $value
     */
    public function osVersion(?string $value): self
    {
        $this->instance->setOsVersion($value);
        return $this;
    }

    /**
     * Sets other Device Information field.
     *
     * @param string|null $value
     */
    public function otherDeviceInformation(?string $value): self
    {
        $this->instance->setOtherDeviceInformation($value);
        return $this;
    }

    /**
     * Initializes a new Device Detail object.
     */
    public function build(): DeviceDetail
    {
        return CoreHelper::clone($this->instance);
    }
}
