<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellEVLib\Models\FaultResponseFault;
use ShellEVLib\Models\FaultResponseFaultDetail;

/**
 * Builder for model FaultResponseFault
 *
 * @see FaultResponseFault
 */
class FaultResponseFaultBuilder
{
    /**
     * @var FaultResponseFault
     */
    private $instance;

    private function __construct(FaultResponseFault $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new fault response fault Builder object.
     */
    public static function init(): self
    {
        return new self(new FaultResponseFault());
    }

    /**
     * Sets faultstring field.
     */
    public function faultstring(?string $value): self
    {
        $this->instance->setFaultstring($value);
        return $this;
    }

    /**
     * Sets detail field.
     */
    public function detail(?FaultResponseFaultDetail $value): self
    {
        $this->instance->setDetail($value);
        return $this;
    }

    /**
     * Initializes a new fault response fault object.
     */
    public function build(): FaultResponseFault
    {
        return CoreHelper::clone($this->instance);
    }
}
