<?php

declare(strict_types=1);

/*
 * ShellSmartPayAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellSmartPayAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellSmartPayAPILib\Models\Fault;
use ShellSmartPayAPILib\Models\FaultResponse;

/**
 * Builder for model FaultResponse
 *
 * @see FaultResponse
 */
class FaultResponseBuilder
{
    /**
     * @var FaultResponse
     */
    private $instance;

    private function __construct(FaultResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Fault Response Builder object.
     */
    public static function init(): self
    {
        return new self(new FaultResponse());
    }

    /**
     * Sets fault field.
     *
     * @param Fault|null $value
     */
    public function fault(?Fault $value): self
    {
        $this->instance->setFault($value);
        return $this;
    }

    /**
     * Initializes a new Fault Response object.
     */
    public function build(): FaultResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
