<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellEVLib\Models\FaultResponse;
use ShellEVLib\Models\FaultResponseFault;

/**
 * Builder for model FaultResponse
 *
 * @see FaultResponse
 */
class FaultResponseBuilder
{
    /**
     * @var FaultResponse
     */
    private $instance;

    private function __construct(FaultResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new fault response Builder object.
     */
    public static function init(): self
    {
        return new self(new FaultResponse());
    }

    /**
     * Sets fault field.
     */
    public function fault(?FaultResponseFault $value): self
    {
        $this->instance->setFault($value);
        return $this;
    }

    /**
     * Initializes a new fault response object.
     */
    public function build(): FaultResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
