<?php

declare(strict_types=1);

/*
 * ShellSmartPayAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellSmartPayAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellSmartPayAPILib\Models\FinaliseFuelingRequest;
use ShellSmartPayAPILib\Models\Payment;
use ShellSmartPayAPILib\Models\Product;

/**
 * Builder for model FinaliseFuelingRequest
 *
 * @see FinaliseFuelingRequest
 */
class FinaliseFuelingRequestBuilder
{
    /**
     * @var FinaliseFuelingRequest
     */
    private $instance;

    private function __construct(FinaliseFuelingRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Finalise Fueling Request Builder object.
     */
    public static function init(): self
    {
        return new self(new FinaliseFuelingRequest());
    }

    /**
     * Sets site Name field.
     *
     * @param string|null $value
     */
    public function siteName(?string $value): self
    {
        $this->instance->setSiteName($value);
        return $this;
    }

    /**
     * Sets timestamp field.
     *
     * @param int|null $value
     */
    public function timestamp(?int $value): self
    {
        $this->instance->setTimestamp($value);
        return $this;
    }

    /**
     * Sets volume Quantity field.
     *
     * @param float|null $value
     */
    public function volumeQuantity(?float $value): self
    {
        $this->instance->setVolumeQuantity($value);
        return $this;
    }

    /**
     * Sets volume Unit field.
     *
     * @param string|null $value
     */
    public function volumeUnit(?string $value): self
    {
        $this->instance->setVolumeUnit($value);
        return $this;
    }

    /**
     * Sets final Price field.
     *
     * @param float|null $value
     */
    public function finalPrice(?float $value): self
    {
        $this->instance->setFinalPrice($value);
        return $this;
    }

    /**
     * Sets currency field.
     *
     * @param string|null $value
     */
    public function currency(?string $value): self
    {
        $this->instance->setCurrency($value);
        return $this;
    }

    /**
     * Sets status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets site Address field.
     *
     * @param string|null $value
     */
    public function siteAddress(?string $value): self
    {
        $this->instance->setSiteAddress($value);
        return $this;
    }

    /**
     * Sets original Price field.
     *
     * @param float|null $value
     */
    public function originalPrice(?float $value): self
    {
        $this->instance->setOriginalPrice($value);
        return $this;
    }

    /**
     * Sets discount field.
     *
     * @param float|null $value
     */
    public function discount(?float $value): self
    {
        $this->instance->setDiscount($value);
        return $this;
    }

    /**
     * Sets payment field.
     *
     * @param Payment|null $value
     */
    public function payment(?Payment $value): self
    {
        $this->instance->setPayment($value);
        return $this;
    }

    /**
     * Sets products field.
     *
     * @param Product[]|null $value
     */
    public function products(?array $value): self
    {
        $this->instance->setProducts($value);
        return $this;
    }

    /**
     * Sets mpp Transaction Id field.
     *
     * @param string|null $value
     */
    public function mppTransactionId(?string $value): self
    {
        $this->instance->setMppTransactionId($value);
        return $this;
    }

    /**
     * Initializes a new Finalise Fueling Request object.
     */
    public function build(): FinaliseFuelingRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
