<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellEVLib\Models\FinaliseFuelingRequestPayment;

/**
 * Builder for model FinaliseFuelingRequestPayment
 *
 * @see FinaliseFuelingRequestPayment
 */
class FinaliseFuelingRequestPaymentBuilder
{
    /**
     * @var FinaliseFuelingRequestPayment
     */
    private $instance;

    private function __construct(FinaliseFuelingRequestPayment $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new finalise fueling request payment Builder object.
     */
    public static function init(): self
    {
        return new self(new FinaliseFuelingRequestPayment());
    }

    /**
     * Sets method field.
     */
    public function method(?string $value): self
    {
        $this->instance->setMethod($value);
        return $this;
    }

    /**
     * Sets card id field.
     */
    public function cardId(?string $value): self
    {
        $this->instance->setCardId($value);
        return $this;
    }

    /**
     * Sets card last digits field.
     */
    public function cardLastDigits(?string $value): self
    {
        $this->instance->setCardLastDigits($value);
        return $this;
    }

    /**
     * Initializes a new finalise fueling request payment object.
     */
    public function build(): FinaliseFuelingRequestPayment
    {
        return CoreHelper::clone($this->instance);
    }
}
