<?php

declare(strict_types=1);

/*
 * ShellSmartPayAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellSmartPayAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellSmartPayAPILib\Models\Loc;

/**
 * Builder for model Loc
 *
 * @see Loc
 */
class LocBuilder
{
    /**
     * @var Loc
     */
    private $instance;

    private function __construct(Loc $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Loc Builder object.
     *
     * @param string $country
     * @param string $ccode
     */
    public static function init(string $country, string $ccode): self
    {
        return new self(new Loc($country, $ccode));
    }

    /**
     * Sets street field.
     *
     * @param string|null $value
     */
    public function street(?string $value): self
    {
        $this->instance->setStreet($value);
        return $this;
    }

    /**
     * Sets pc field.
     *
     * @param string|null $value
     */
    public function pc(?string $value): self
    {
        $this->instance->setPc($value);
        return $this;
    }

    /**
     * Sets city field.
     *
     * @param string|null $value
     */
    public function city(?string $value): self
    {
        $this->instance->setCity($value);
        return $this;
    }

    /**
     * Sets region field.
     *
     * @param string|null $value
     */
    public function region(?string $value): self
    {
        $this->instance->setRegion($value);
        return $this;
    }

    /**
     * Initializes a new Loc object.
     */
    public function build(): Loc
    {
        return CoreHelper::clone($this->instance);
    }
}
