<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellEVLib\Models\LoyaltyDetails;

/**
 * Builder for model LoyaltyDetails
 *
 * @see LoyaltyDetails
 */
class LoyaltyDetailsBuilder
{
    /**
     * @var LoyaltyDetails
     */
    private $instance;

    private function __construct(LoyaltyDetails $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new loyalty details Builder object.
     */
    public static function init(string $loyaltyId, string $loyaltyType): self
    {
        return new self(new LoyaltyDetails($loyaltyId, $loyaltyType));
    }

    /**
     * Initializes a new loyalty details object.
     */
    public function build(): LoyaltyDetails
    {
        return CoreHelper::clone($this->instance);
    }
}
