<?php

declare(strict_types=1);

/*
 * ShellSmartPayAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellSmartPayAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellSmartPayAPILib\Models\CollectingCompany;
use ShellSmartPayAPILib\Models\MobilePaymentRegistrationRequest;

/**
 * Builder for model MobilePaymentRegistrationRequest
 *
 * @see MobilePaymentRegistrationRequest
 */
class MobilePaymentRegistrationRequestBuilder
{
    /**
     * @var MobilePaymentRegistrationRequest
     */
    private $instance;

    private function __construct(MobilePaymentRegistrationRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Mobile Payment Registration Request Builder object.
     *
     * @param string $referenceId
     * @param string $pan
     * @param string $panExpiry
     * @param int $period
     * @param string $accountId
     * @param string $payerId
     * @param string $colCoId
     * @param CollectingCompany[] $collectingCompanies
     */
    public static function init(
        string $referenceId,
        string $pan,
        string $panExpiry,
        int $period,
        string $accountId,
        string $payerId,
        string $colCoId,
        array $collectingCompanies
    ): self {
        return new self(new MobilePaymentRegistrationRequest(
            $referenceId,
            $pan,
            $panExpiry,
            $period,
            $accountId,
            $payerId,
            $colCoId,
            $collectingCompanies
        ));
    }

    /**
     * Initializes a new Mobile Payment Registration Request object.
     */
    public function build(): MobilePaymentRegistrationRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
