<?php

declare(strict_types=1);

/*
 * ShellSmartPayAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellSmartPayAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellSmartPayAPILib\Models\MppAccesTokenResponse;

/**
 * Builder for model MppAccesTokenResponse
 *
 * @see MppAccesTokenResponse
 */
class MppAccesTokenResponseBuilder
{
    /**
     * @var MppAccesTokenResponse
     */
    private $instance;

    private function __construct(MppAccesTokenResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Mpp Acces Token Response Builder object.
     */
    public static function init(): self
    {
        return new self(new MppAccesTokenResponse());
    }

    /**
     * Sets access token field.
     *
     * @param string|null $value
     */
    public function accessToken(?string $value): self
    {
        $this->instance->setAccessToken($value);
        return $this;
    }

    /**
     * Sets token type field.
     *
     * @param string|null $value
     */
    public function tokenType(?string $value): self
    {
        $this->instance->setTokenType($value);
        return $this;
    }

    /**
     * Sets expires in field.
     *
     * @param int|null $value
     */
    public function expiresIn(?int $value): self
    {
        $this->instance->setExpiresIn($value);
        return $this;
    }

    /**
     * Sets scope field.
     *
     * @param string|null $value
     */
    public function scope(?string $value): self
    {
        $this->instance->setScope($value);
        return $this;
    }

    /**
     * Initializes a new Mpp Acces Token Response object.
     */
    public function build(): MppAccesTokenResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
