<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellEVLib\Models\MppError;

/**
 * Builder for model MppError
 *
 * @see MppError
 */
class MppErrorBuilder
{
    /**
     * @var MppError
     */
    private $instance;

    private function __construct(MppError $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new mpp error Builder object.
     */
    public static function init(): self
    {
        return new self(new MppError());
    }

    /**
     * Sets message field.
     */
    public function message(?string $value): self
    {
        $this->instance->setMessage($value);
        return $this;
    }

    /**
     * Sets reason field.
     */
    public function reason(?string $value): self
    {
        $this->instance->setReason($value);
        return $this;
    }

    /**
     * Sets subject field.
     */
    public function subject(?string $value): self
    {
        $this->instance->setSubject($value);
        return $this;
    }

    /**
     * Sets subject type field.
     */
    public function subjectType(?string $value): self
    {
        $this->instance->setSubjectType($value);
        return $this;
    }

    /**
     * Sets type field.
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Initializes a new mpp error object.
     */
    public function build(): MppError
    {
        return CoreHelper::clone($this->instance);
    }
}
