<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellEVLib\Models\MppTokenRequestBody;

/**
 * Builder for model MppTokenRequestBody
 *
 * @see MppTokenRequestBody
 */
class MppTokenRequestBodyBuilder
{
    /**
     * @var MppTokenRequestBody
     */
    private $instance;

    private function __construct(MppTokenRequestBody $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new mpp token request body Builder object.
     */
    public static function init(string $grantType, string $clientId, string $clientSecret): self
    {
        return new self(new MppTokenRequestBody($grantType, $clientId, $clientSecret));
    }

    /**
     * Initializes a new mpp token request body object.
     */
    public function build(): MppTokenRequestBody
    {
        return CoreHelper::clone($this->instance);
    }
}
