<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellEVLib\Models\OauthTokenPostRequestBody;

/**
 * Builder for model OauthTokenPostRequestBody
 *
 * @see OauthTokenPostRequestBody
 */
class OauthTokenPostRequestBodyBuilder
{
    /**
     * @var OauthTokenPostRequestBody
     */
    private $instance;

    private function __construct(OauthTokenPostRequestBody $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new oauth token post request body Builder object.
     */
    public static function init(string $grantType, string $clientId, string $clientSecret): self
    {
        return new self(new OauthTokenPostRequestBody($grantType, $clientId, $clientSecret));
    }

    /**
     * Initializes a new oauth token post request body object.
     */
    public function build(): OauthTokenPostRequestBody
    {
        return CoreHelper::clone($this->instance);
    }
}
