<?php

declare(strict_types=1);

/*
 * ShellSmartPayAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellSmartPayAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellSmartPayAPILib\Models\OpeningHour;

/**
 * Builder for model OpeningHour
 *
 * @see OpeningHour
 */
class OpeningHourBuilder
{
    /**
     * @var OpeningHour
     */
    private $instance;

    private function __construct(OpeningHour $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Opening Hour Builder object.
     */
    public static function init(): self
    {
        return new self(new OpeningHour());
    }

    /**
     * Sets Closing From Hours field.
     *
     * @param string|null $value
     */
    public function closingFromHours(?string $value): self
    {
        $this->instance->setClosingFromHours($value);
        return $this;
    }

    /**
     * Sets Closing From Minutes field.
     *
     * @param string|null $value
     */
    public function closingFromMinutes(?string $value): self
    {
        $this->instance->setClosingFromMinutes($value);
        return $this;
    }

    /**
     * Sets Closing To Hours field.
     *
     * @param string|null $value
     */
    public function closingToHours(?string $value): self
    {
        $this->instance->setClosingToHours($value);
        return $this;
    }

    /**
     * Sets Closing To Minutes field.
     *
     * @param string|null $value
     */
    public function closingToMinutes(?string $value): self
    {
        $this->instance->setClosingToMinutes($value);
        return $this;
    }

    /**
     * Sets From Day field.
     *
     * @param string|null $value
     */
    public function fromDay(?string $value): self
    {
        $this->instance->setFromDay($value);
        return $this;
    }

    /**
     * Sets Opening From Hours field.
     *
     * @param string|null $value
     */
    public function openingFromHours(?string $value): self
    {
        $this->instance->setOpeningFromHours($value);
        return $this;
    }

    /**
     * Sets Opening From Minutes field.
     *
     * @param string|null $value
     */
    public function openingFromMinutes(?string $value): self
    {
        $this->instance->setOpeningFromMinutes($value);
        return $this;
    }

    /**
     * Sets Opening To Hours field.
     *
     * @param string|null $value
     */
    public function openingToHours(?string $value): self
    {
        $this->instance->setOpeningToHours($value);
        return $this;
    }

    /**
     * Sets Opening To Minutes field.
     *
     * @param string|null $value
     */
    public function openingToMinutes(?string $value): self
    {
        $this->instance->setOpeningToMinutes($value);
        return $this;
    }

    /**
     * Sets To Day field.
     *
     * @param string|null $value
     */
    public function toDay(?string $value): self
    {
        $this->instance->setToDay($value);
        return $this;
    }

    /**
     * Initializes a new Opening Hour object.
     */
    public function build(): OpeningHour
    {
        return CoreHelper::clone($this->instance);
    }
}
