<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellEVLib\Models\PartnerTokenRequestBody;

/**
 * Builder for model PartnerTokenRequestBody
 *
 * @see PartnerTokenRequestBody
 */
class PartnerTokenRequestBodyBuilder
{
    /**
     * @var PartnerTokenRequestBody
     */
    private $instance;

    private function __construct(PartnerTokenRequestBody $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new partner token request body Builder object.
     */
    public static function init(string $grantType, string $clientId, string $clientSecret): self
    {
        return new self(new PartnerTokenRequestBody($grantType, $clientId, $clientSecret));
    }

    /**
     * Initializes a new partner token request body object.
     */
    public function build(): PartnerTokenRequestBody
    {
        return CoreHelper::clone($this->instance);
    }
}
