<?php

declare(strict_types=1);

/*
 * ShellSmartPayAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellSmartPayAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellSmartPayAPILib\Models\PaymentEnablementResponse;

/**
 * Builder for model PaymentEnablementResponse
 *
 * @see PaymentEnablementResponse
 */
class PaymentEnablementResponseBuilder
{
    /**
     * @var PaymentEnablementResponse
     */
    private $instance;

    private function __construct(PaymentEnablementResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Payment Enablement Response Builder object.
     *
     * @param string $dpanLast4
     */
    public static function init(string $dpanLast4): self
    {
        return new self(new PaymentEnablementResponse($dpanLast4));
    }

    /**
     * Initializes a new Payment Enablement Response object.
     */
    public function build(): PaymentEnablementResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
