<?php

declare(strict_types=1);

/*
 * ShellSmartPayAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellSmartPayAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellSmartPayAPILib\Models\PaymentProperties;

/**
 * Builder for model PaymentProperties
 *
 * @see PaymentProperties
 */
class PaymentPropertiesBuilder
{
    /**
     * @var PaymentProperties
     */
    private $instance;

    private function __construct(PaymentProperties $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Payment Properties Builder object.
     *
     * @param string $cardIdentifier
     */
    public static function init(string $cardIdentifier): self
    {
        return new self(new PaymentProperties($cardIdentifier));
    }

    /**
     * Sets payment Type field.
     *
     * @param string|null $value
     */
    public function paymentType(?string $value): self
    {
        $this->instance->setPaymentType($value);
        return $this;
    }

    /**
     * Sets client Metadata Id field.
     *
     * @param string|null $value
     */
    public function clientMetadataId(?string $value): self
    {
        $this->instance->setClientMetadataId($value);
        return $this;
    }

    /**
     * Sets token field.
     *
     * @param string|null $value
     */
    public function token(?string $value): self
    {
        $this->instance->setToken($value);
        return $this;
    }

    /**
     * Sets identifier field.
     *
     * @param string|null $value
     */
    public function identifier(?string $value): self
    {
        $this->instance->setIdentifier($value);
        return $this;
    }

    /**
     * Sets network field.
     *
     * @param string|null $value
     */
    public function network(?string $value): self
    {
        $this->instance->setNetwork($value);
        return $this;
    }

    /**
     * Sets odometer field.
     *
     * @param string|null $value
     */
    public function odometer(?string $value): self
    {
        $this->instance->setOdometer($value);
        return $this;
    }

    /**
     * Sets fleet Id field.
     *
     * @param string|null $value
     */
    public function fleetId(?string $value): self
    {
        $this->instance->setFleetId($value);
        return $this;
    }

    /**
     * Sets external Ref Id field.
     *
     * @param string|null $value
     */
    public function externalRefId(?string $value): self
    {
        $this->instance->setExternalRefId($value);
        return $this;
    }

    /**
     * Initializes a new Payment Properties object.
     */
    public function build(): PaymentProperties
    {
        return CoreHelper::clone($this->instance);
    }
}
