<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellEVLib\Models\PaymentDetailsItems;
use ShellEVLib\Models\PaymentProperties;

/**
 * Builder for model PaymentDetailsItems
 *
 * @see PaymentDetailsItems
 */
class PaymentDetailsItemsBuilder
{
    /**
     * @var PaymentDetailsItems
     */
    private $instance;

    private function __construct(PaymentDetailsItems $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new payment details items Builder object.
     */
    public static function init(string $paymentMethodId, PaymentProperties $paymentProperties): self
    {
        return new self(new PaymentDetailsItems($paymentMethodId, $paymentProperties));
    }

    /**
     * Sets payment category field.
     */
    public function paymentCategory(?string $value): self
    {
        $this->instance->setPaymentCategory($value);
        return $this;
    }

    /**
     * Initializes a new payment details items object.
     */
    public function build(): PaymentDetailsItems
    {
        return CoreHelper::clone($this->instance);
    }
}
