<?php

declare(strict_types=1);

/*
 * ShellSmartPayAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellSmartPayAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellSmartPayAPILib\Models\DeviceDetail;
use ShellSmartPayAPILib\Models\LoyaltyDetails;
use ShellSmartPayAPILib\Models\PaymentDetails;
use ShellSmartPayAPILib\Models\PrepareFuelingRequest;

/**
 * Builder for model PrepareFuelingRequest
 *
 * @see PrepareFuelingRequest
 */
class PrepareFuelingRequestBuilder
{
    /**
     * @var PrepareFuelingRequest
     */
    private $instance;

    private function __construct(PrepareFuelingRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Prepare Fueling Request Builder object.
     *
     * @param float $latitude
     * @param float $longitude
     * @param string $stationId
     * @param string $pumpId
     * @param string $sourceApplication
     * @param PaymentDetails $paymentDetails
     */
    public static function init(
        float $latitude,
        float $longitude,
        string $stationId,
        string $pumpId,
        string $sourceApplication,
        PaymentDetails $paymentDetails
    ): self {
        return new self(
            new PrepareFuelingRequest(
                $latitude,
                $longitude,
                $stationId,
                $pumpId,
                $sourceApplication,
                $paymentDetails
            )
        );
    }

    /**
     * Sets maximum Fueling Amount field.
     *
     * @param float|null $value
     */
    public function maximumFuelingAmount(?float $value): self
    {
        $this->instance->setMaximumFuelingAmount($value);
        return $this;
    }

    /**
     * Sets loyalty Details field.
     *
     * @param LoyaltyDetails[]|null $value
     */
    public function loyaltyDetails(?array $value): self
    {
        $this->instance->setLoyaltyDetails($value);
        return $this;
    }

    /**
     * Sets device Type field.
     *
     * @param string|null $value
     */
    public function deviceType(?string $value): self
    {
        $this->instance->setDeviceType($value);
        return $this;
    }

    /**
     * Sets device Details field.
     *
     * @param DeviceDetail[]|null $value
     */
    public function deviceDetails(?array $value): self
    {
        $this->instance->setDeviceDetails($value);
        return $this;
    }

    /**
     * Initializes a new Prepare Fueling Request object.
     */
    public function build(): PrepareFuelingRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
