<?php

declare(strict_types=1);

/*
 * ShellSmartPayAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellSmartPayAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellSmartPayAPILib\Models\PrepareFuelingResponse;

/**
 * Builder for model PrepareFuelingResponse
 *
 * @see PrepareFuelingResponse
 */
class PrepareFuelingResponseBuilder
{
    /**
     * @var PrepareFuelingResponse
     */
    private $instance;

    private function __construct(PrepareFuelingResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Prepare Fueling Response Builder object.
     *
     * @param string $mppTransactionId
     */
    public static function init(string $mppTransactionId): self
    {
        return new self(new PrepareFuelingResponse($mppTransactionId));
    }

    /**
     * Sets products field.
     *
     * @param string[]|null $value
     */
    public function products(?array $value): self
    {
        $this->instance->setProducts($value);
        return $this;
    }

    /**
     * Initializes a new Prepare Fueling Response object.
     */
    public function build(): PrepareFuelingResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
