<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellEVLib\Models\PrepareFuelingRequestDeviceDetailsItems;

/**
 * Builder for model PrepareFuelingRequestDeviceDetailsItems
 *
 * @see PrepareFuelingRequestDeviceDetailsItems
 */
class PrepareFuelingRequestDeviceDetailsItemsBuilder
{
    /**
     * @var PrepareFuelingRequestDeviceDetailsItems
     */
    private $instance;

    private function __construct(PrepareFuelingRequestDeviceDetailsItems $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new prepare fueling request device details items Builder object.
     */
    public static function init(): self
    {
        return new self(new PrepareFuelingRequestDeviceDetailsItems());
    }

    /**
     * Sets device id field.
     */
    public function deviceId(?string $value): self
    {
        $this->instance->setDeviceId($value);
        return $this;
    }

    /**
     * Sets model field.
     */
    public function model(?string $value): self
    {
        $this->instance->setModel($value);
        return $this;
    }

    /**
     * Sets os version field.
     */
    public function osVersion(?string $value): self
    {
        $this->instance->setOsVersion($value);
        return $this;
    }

    /**
     * Sets other device information field.
     */
    public function otherDeviceInformation(?string $value): self
    {
        $this->instance->setOtherDeviceInformation($value);
        return $this;
    }

    /**
     * Initializes a new prepare fueling request device details items object.
     */
    public function build(): PrepareFuelingRequestDeviceDetailsItems
    {
        return CoreHelper::clone($this->instance);
    }
}
