<?php

declare(strict_types=1);

/*
 * ShellSmartPayAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellSmartPayAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellSmartPayAPILib\Models\Product;

/**
 * Builder for model Product
 *
 * @see Product
 */
class ProductBuilder
{
    /**
     * @var Product
     */
    private $instance;

    private function __construct(Product $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Product Builder object.
     */
    public static function init(): self
    {
        return new self(new Product());
    }

    /**
     * Sets product Id field.
     *
     * @param string|null $value
     */
    public function productId(?string $value): self
    {
        $this->instance->setProductId($value);
        return $this;
    }

    /**
     * Sets product Name field.
     *
     * @param string|null $value
     */
    public function productName(?string $value): self
    {
        $this->instance->setProductName($value);
        return $this;
    }

    /**
     * Sets unit Price field.
     *
     * @param float|null $value
     */
    public function unitPrice(?float $value): self
    {
        $this->instance->setUnitPrice($value);
        return $this;
    }

    /**
     * Initializes a new Product object.
     */
    public function build(): Product
    {
        return CoreHelper::clone($this->instance);
    }
}
