<?php

declare(strict_types=1);

/*
 * ShellSmartPayAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellSmartPayAPILib\Exceptions;

use ShellSmartPayAPILib\ApiHelper;

class MppAccesTokenErrorResponseException extends ApiException
{
    /**
     * @var string
     */
    private $error;

    /**
     * @var string
     */
    private $errorCode;

    /**
     * @var string|null
     */
    private $errorDescription;

    /**
     * @param string $reason
     * @param \ShellSmartPayAPILib\Http\HttpRequest $request
     * @param \ShellSmartPayAPILib\Http\HttpResponse $response
     * @param string $error
     * @param string $errorCode
     */
    public function __construct(
        string $reason,
        \ShellSmartPayAPILib\Http\HttpRequest $request,
        \ShellSmartPayAPILib\Http\HttpResponse $response,
        string $error,
        string $errorCode
    ) {
        parent::__construct($reason, $request, $response);
        $this->error = $error;
        $this->errorCode = $errorCode;
    }

    /**
     * Returns Error.
     * error code or short description
     */
    public function getError(): string
    {
        return $this->error;
    }

    /**
     * Sets Error.
     * error code or short description
     *
     * @required
     * @maps error
     */
    public function setError(string $error): void
    {
        $this->error = $error;
    }

    /**
     * Returns Error Code.
     * error code or short description due to invalid request or invalid client ID
     */
    public function getErrorCode(): string
    {
        return $this->errorCode;
    }

    /**
     * Sets Error Code.
     * error code or short description due to invalid request or invalid client ID
     *
     * @required
     * @maps error_code
     */
    public function setErrorCode(string $errorCode): void
    {
        $this->errorCode = $errorCode;
    }

    /**
     * Returns Error Description.
     * Description of the error
     */
    public function getErrorDescription(): ?string
    {
        return $this->errorDescription;
    }

    /**
     * Sets Error Description.
     * Description of the error
     *
     * @maps error_description
     */
    public function setErrorDescription(?string $errorDescription): void
    {
        $this->errorDescription = $errorDescription;
    }

    /**
     * Converts the MppAccesTokenErrorResponseException object to a human-readable string representation.
     *
     * @return string The string representation of the MppAccesTokenErrorResponseException object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'MppAccesTokenErrorResponseException',
            [
                'error' => $this->error,
                'errorCode' => $this->errorCode,
                'errorDescription' => $this->errorDescription
            ],
            parent::__toString()
        );
    }
}
