<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Exceptions;

class MppAccesTokenErrorResponseException extends ApiException
{
    /**
     * @var string
     */
    private $error;

    /**
     * @var string
     */
    private $errorCode;

    /**
     * @var string|null
     */
    private $errorDescription;

    /**
     * @param string $reason
     * @param \ShellEVLib\Http\HttpRequest $request
     * @param \ShellEVLib\Http\HttpResponse $response
     * @param string $error
     * @param string $errorCode
     */
    public function __construct(
        string $reason,
        \ShellEVLib\Http\HttpRequest $request,
        \ShellEVLib\Http\HttpResponse $response,
        string $error,
        string $errorCode
    ) {
        parent::__construct($reason, $request, $response);
        $this->error = $error;
        $this->errorCode = $errorCode;
    }

    /**
     * Returns Error.
     * error code or short description
     */
    public function getError(): string
    {
        return $this->error;
    }

    /**
     * Sets Error.
     * error code or short description
     *
     * @required
     * @maps error
     */
    public function setError(string $error): void
    {
        $this->error = $error;
    }

    /**
     * Returns Error Code.
     * error code or short description due to invalid request or invalid client ID
     */
    public function getErrorCode(): string
    {
        return $this->errorCode;
    }

    /**
     * Sets Error Code.
     * error code or short description due to invalid request or invalid client ID
     *
     * @required
     * @maps error_code
     */
    public function setErrorCode(string $errorCode): void
    {
        $this->errorCode = $errorCode;
    }

    /**
     * Returns Error Description.
     * Description of the error
     */
    public function getErrorDescription(): ?string
    {
        return $this->errorDescription;
    }

    /**
     * Sets Error Description.
     * Description of the error
     *
     * @maps error_description
     */
    public function setErrorDescription(?string $errorDescription): void
    {
        $this->errorDescription = $errorDescription;
    }
}
