<?php

declare(strict_types=1);

/*
 * ShellSmartPayAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellSmartPayAPILib\Exceptions;

use ShellSmartPayAPILib\ApiHelper;

class StationLocatorNotFoundException extends ApiException
{
    /**
     * @var string|null
     */
    private $errorCode;

    /**
     * @var string|null
     */
    private $errorDescription;

    /**
     * Returns Error Code.
     */
    public function getErrorCode(): ?string
    {
        return $this->errorCode;
    }

    /**
     * Sets Error Code.
     *
     * @maps errorCode
     */
    public function setErrorCode(?string $errorCode): void
    {
        $this->errorCode = $errorCode;
    }

    /**
     * Returns Error Description.
     */
    public function getErrorDescription(): ?string
    {
        return $this->errorDescription;
    }

    /**
     * Sets Error Description.
     *
     * @maps errorDescription
     */
    public function setErrorDescription(?string $errorDescription): void
    {
        $this->errorDescription = $errorDescription;
    }

    /**
     * Converts the StationLocatorNotFoundException object to a human-readable string representation.
     *
     * @return string The string representation of the StationLocatorNotFoundException object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'StationLocatorNotFoundException',
            ['errorCode' => $this->errorCode, 'errorDescription' => $this->errorDescription],
            parent::__toString()
        );
    }
}
