<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models;

use stdClass;

class AccessTokenResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $accessToken;

    /**
     * @var string|null
     */
    private $expiresIn;

    /**
     * @var string|null
     */
    private $tokenType = 'Bearer';

    /**
     * Returns Access Token.
     * It is the token used for the requests that required an authenticated user. This will be used for all
     * the callback URLs.
     */
    public function getAccessToken(): ?string
    {
        return $this->accessToken;
    }

    /**
     * Sets Access Token.
     * It is the token used for the requests that required an authenticated user. This will be used for all
     * the callback URLs.
     *
     * @maps access_token
     */
    public function setAccessToken(?string $accessToken): void
    {
        $this->accessToken = $accessToken;
    }

    /**
     * Returns Expires In.
     * validity of the access token in seconds
     */
    public function getExpiresIn(): ?string
    {
        return $this->expiresIn;
    }

    /**
     * Sets Expires In.
     * validity of the access token in seconds
     *
     * @maps expires_in
     */
    public function setExpiresIn(?string $expiresIn): void
    {
        $this->expiresIn = $expiresIn;
    }

    /**
     * Returns Token Type.
     * Type of token provided
     */
    public function getTokenType(): ?string
    {
        return $this->tokenType;
    }

    /**
     * Sets Token Type.
     * Type of token provided
     *
     * @maps token_type
     */
    public function setTokenType(?string $tokenType): void
    {
        $this->tokenType = $tokenType;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->accessToken)) {
            $json['access_token'] = $this->accessToken;
        }
        if (isset($this->expiresIn)) {
            $json['expires_in']   = $this->expiresIn;
        }
        if (isset($this->tokenType)) {
            $json['token_type']   = $this->tokenType;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
