<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models;

use stdClass;

class CancelFuelingRequest implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $mppTransactionId;

    /**
     * @var string|null
     */
    private $reasonCode;

    /**
     * Returns Mpp Transaction Id.
     */
    public function getMppTransactionId(): ?string
    {
        return $this->mppTransactionId;
    }

    /**
     * Sets Mpp Transaction Id.
     *
     * @maps mppTransactionId
     */
    public function setMppTransactionId(?string $mppTransactionId): void
    {
        $this->mppTransactionId = $mppTransactionId;
    }

    /**
     * Returns Reason Code.
     */
    public function getReasonCode(): ?string
    {
        return $this->reasonCode;
    }

    /**
     * Sets Reason Code.
     *
     * @maps reasonCode
     */
    public function setReasonCode(?string $reasonCode): void
    {
        $this->reasonCode = $reasonCode;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->mppTransactionId)) {
            $json['mppTransactionId'] = $this->mppTransactionId;
        }
        if (isset($this->reasonCode)) {
            $json['reasonCode']       = $this->reasonCode;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
