<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models;

use stdClass;

class FaultResponseFault implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $faultstring;

    /**
     * @var FaultResponseFaultDetail|null
     */
    private $detail;

    /**
     * Returns Faultstring.
     * The description of the error.
     */
    public function getFaultstring(): ?string
    {
        return $this->faultstring;
    }

    /**
     * Sets Faultstring.
     * The description of the error.
     *
     * @maps faultstring
     */
    public function setFaultstring(?string $faultstring): void
    {
        $this->faultstring = $faultstring;
    }

    /**
     * Returns Detail.
     */
    public function getDetail(): ?FaultResponseFaultDetail
    {
        return $this->detail;
    }

    /**
     * Sets Detail.
     *
     * @maps detail
     */
    public function setDetail(?FaultResponseFaultDetail $detail): void
    {
        $this->detail = $detail;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->faultstring)) {
            $json['faultstring'] = $this->faultstring;
        }
        if (isset($this->detail)) {
            $json['detail']      = $this->detail;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
