<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models;

use stdClass;

class FinaliseFuelingRequestPayment implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $method;

    /**
     * @var string|null
     */
    private $cardId;

    /**
     * @var string|null
     */
    private $cardLastDigits;

    /**
     * Returns Method.
     */
    public function getMethod(): ?string
    {
        return $this->method;
    }

    /**
     * Sets Method.
     *
     * @maps method
     */
    public function setMethod(?string $method): void
    {
        $this->method = $method;
    }

    /**
     * Returns Card Id.
     */
    public function getCardId(): ?string
    {
        return $this->cardId;
    }

    /**
     * Sets Card Id.
     *
     * @maps cardId
     */
    public function setCardId(?string $cardId): void
    {
        $this->cardId = $cardId;
    }

    /**
     * Returns Card Last Digits.
     */
    public function getCardLastDigits(): ?string
    {
        return $this->cardLastDigits;
    }

    /**
     * Sets Card Last Digits.
     *
     * @maps cardLastDigits
     */
    public function setCardLastDigits(?string $cardLastDigits): void
    {
        $this->cardLastDigits = $cardLastDigits;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->method)) {
            $json['method']         = $this->method;
        }
        if (isset($this->cardId)) {
            $json['cardId']         = $this->cardId;
        }
        if (isset($this->cardLastDigits)) {
            $json['cardLastDigits'] = $this->cardLastDigits;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
