<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models;

use stdClass;

class OauthTokenPostRequestBody implements \JsonSerializable
{
    /**
     * @var string
     */
    private $grantType;

    /**
     * @var string
     */
    private $clientId;

    /**
     * @var string
     */
    private $clientSecret;

    /**
     * @param string $grantType
     * @param string $clientId
     * @param string $clientSecret
     */
    public function __construct(string $grantType, string $clientId, string $clientSecret)
    {
        $this->grantType = $grantType;
        $this->clientId = $clientId;
        $this->clientSecret = $clientSecret;
    }

    /**
     * Returns Grant Type.
     * In OAuth 2.0, the term grant typee refers to the way an application gets an access token. OAuth 2.0
     * defines several grant types, including the authorization code flow.
     */
    public function getGrantType(): string
    {
        return $this->grantType;
    }

    /**
     * Sets Grant Type.
     * In OAuth 2.0, the term grant typee refers to the way an application gets an access token. OAuth 2.0
     * defines several grant types, including the authorization code flow.
     *
     * @required
     * @maps grant_type
     */
    public function setGrantType(string $grantType): void
    {
        $this->grantType = $grantType;
    }

    /**
     * Returns Client Id.
     * After registering your app, you will receive a client ID and a client secret. The client ID is
     * considered public information, and is used to build login URLs, or included in Javascript source
     * code on a page.
     */
    public function getClientId(): string
    {
        return $this->clientId;
    }

    /**
     * Sets Client Id.
     * After registering your app, you will receive a client ID and a client secret. The client ID is
     * considered public information, and is used to build login URLs, or included in Javascript source
     * code on a page.
     *
     * @required
     * @maps client_id
     */
    public function setClientId(string $clientId): void
    {
        $this->clientId = $clientId;
    }

    /**
     * Returns Client Secret.
     * After registering your app, you will receive a client ID and a client secret. The client ID is
     * considered public information, and is used to build login URLs, or included in Javascript source
     * code on a page. The client secret must be kept confidential.
     */
    public function getClientSecret(): string
    {
        return $this->clientSecret;
    }

    /**
     * Sets Client Secret.
     * After registering your app, you will receive a client ID and a client secret. The client ID is
     * considered public information, and is used to build login URLs, or included in Javascript source
     * code on a page. The client secret must be kept confidential.
     *
     * @required
     * @maps client_secret
     */
    public function setClientSecret(string $clientSecret): void
    {
        $this->clientSecret = $clientSecret;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['grant_type']    = $this->grantType;
        $json['client_id']     = $this->clientId;
        $json['client_secret'] = $this->clientSecret;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
