<?php

declare(strict_types=1);

/*
 * ShellSmartPayAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellSmartPayAPILib;

/**
 * Environments available for API
 */
class Environment
{
    public const TEST = 'Test';

    public const PRODUCTION = 'Production';
}
