<?php

declare(strict_types=1);

/*
 * ShellSmartPayAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellSmartPayAPILib;

/**
 * Baseurl aliases
 */
class Server
{
    public const SHELL = 'Shell';
}
